name: Deployment Test

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      issues: write
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed successfully"

      - name: Run semantic-release
        run: npx semantic-release@^24
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Debug Info Before Release
        run: |
          echo "Current working directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
