name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          preset: "conventionalcommits"
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            revert
            ci
            move
            remove
          disableScopes: false
