name: PR Title Checker

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            docs
            style
            revert
            ci
            test
            chore
            move
            remove
          requireScope: false
          subjectPattern: ^[A-Za-z].+$
          subjectPatternError: |
            PR 제목은 영문으로 시작해야 하며, 비어있지 않아야 합니다.
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false
          wip: false
          errorComment: |
            PR 제목이 semantic 컨벤션에 맞지 않습니다. 다음 형식을 따라주세요:

            type: description

            사용 가능한 타입:
            - feat: 새로운 기능
            - fix: 버그 수정
            - perf: 성능 개선
            - refactor: 리팩토링
            - docs: 문서 수정
            - style: 코드 스타일 변경
            - revert: 변경 되돌리기
            - ci: CI/CD 관련 변경
            - test: 테스트 코드
            - chore: 기타 변경사항
            - move: 파일 이동
            - remove: 파일 삭제
