name: PR Title Checker

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            refactor
            revert
            ci
            docs
            perf
            test
          scopes: |
            breaking
            no-release
          requireScope: false
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false
          wip: false
